nodeLinker: node-modules

npmAuditRegistry: "https://registry.yarnpkg.com"

npmPublishRegistry: "https://artifactory.rakuten-it.com/api/npm/gora-ui-npm-release-local"

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  golf:
    npmRegistryServer: "https://artifactory.rakuten-it.com/api/npm/gora-ui-npm-release-local"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
